### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by yvi1** [hiveliberty/eve-citadel#9]
Здравствуйте. При попытке авторизоваться с дискордом, постоянно выдается ошибка 401 "Неавторизован". Я прошел логин через клиент Евы. Увидел окно Дискорда под названием Alarmer и нажал копку "Авторизовать". Стак трейс прилагаю. Спасибо.

Slim Application Error
The application could not run because of the following error:

Details
Type: GuzzleHttp\Command\Exception\CommandClientException
Message: There was an error executing the getGuildRoles command: Client error: `GET https://discordapp.com/api/v6/guilds/163350993386340352/roles` resulted in a `401 UNAUTHORIZED` response:
File: D:\GitHub\eve-citadel\working\vendor\guzzlehttp\command\src\Exception\CommandException.php
Line: 57
Trace
#0 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\command\src\ServiceClient.php(179): GuzzleHttp\Command\Exception\CommandException::fromPrevious(Object(GuzzleHttp\Command\Command), Object(GuzzleHttp\Exception\ClientException))
#1 [internal function]: GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}()
#2 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Coroutine.php(142): Generator->throw(Object(GuzzleHttp\Exception\ClientException))
#3 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Promise\Coroutine->_handleFailure(Object(GuzzleHttp\Exception\ClientException))
#4 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(2, Object(GuzzleHttp\Exception\ClientException), Array)
#5 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#6 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(98): GuzzleHttp\Promise\TaskQueue->run()
#7 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(125): GuzzleHttp\Handler\CurlMultiHandler->tick()
#8 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#9 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#10 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#11 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#12 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#13 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Coroutine.php(65): GuzzleHttp\Promise\Promise->wait()
#14 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true)
#15 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#16 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#17 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\promises\src\Coroutine.php(85): GuzzleHttp\Promise\Promise->wait(true)
#18 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\command\src\ServiceClient.php(77): GuzzleHttp\Promise\Coroutine->wait()
#19 D:\GitHub\eve-citadel\working\vendor\guzzlehttp\command\src\ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command))
#20 D:\GitHub\eve-citadel\working\vendor\restcord\restcord\src\OverriddenGuzzleClient.php(87): GuzzleHttp\Command\ServiceClient->__call('getGuildRoles', Array)
#21 D:\GitHub\eve-citadel\working\lib\discord.class.php(20): RestCord\OverriddenGuzzleClient->__call('getGuildRoles', Array)
#22 D:\GitHub\eve-citadel\working\app\routes.php(485): DiscordCitadelClient->__construct()
#23 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#24 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#25 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#26 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#28 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\App.php(513): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#29 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#30 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#31 D:\GitHub\eve-citadel\working\vendor\slim\slim\Slim\App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#32 D:\GitHub\eve-citadel\working\public\index.php(34): Slim\App->run()
#33 {main}

**Comment by amakhno** [comment]
Hi,

In the file /lib/eve.class.php change 
const BASE_URL = "https://esi.tech.ccp.is/";
to
const BASE_URL = "https://esi.evetech.net/";

But I've got another (403) error. I'll check it at the weekend, but it doesn't mean that you should face the same problem.
After I fix it, I'm going to create a PR

Artem

**Comment by hiveliberty** [comment]
@yvi1 а ты бота добавил в свой дискорд и дал ему наивысшую роль?
401 UNAUTHORIZED сообщает апи дискорда, что говорит о том, что ботом не всё окей. Либо права, либо его там нет, например.
Ещё рекомендую юзать dev бранч. На данный момент я сам его использую в альянсе.
@amakhno I changed base_url at september 2018.. https://github.com/hiveliberty/eve-citadel/commit/f6506aa60a2289c3ed8b6bd7e6620cae2abd30ff#diff-5feb85a8091bae606a9329c904a3e749
but master branch is outdated today :)

my discord: hiveliberty#2064
